export const allItems = [
  { id: 100, title: "All Departments" },
  { id: 101, title: "Arts & Crafts" },
  { id: 102, title: "Automotive" },
  { id: 103, title: "Baby" },
  { id: 104, title: "Beauty & Personal Care" },
  { id: 105, title: "Books" },
  { id: 106, title: "Computers" },
  { id: 107, title: "Digital Music" },
  { id: 108, title: "Electronics" },
  { id: 109, title: "Garden & Outdoor" },
  { id: 110, title: "Grocery & Gourmet Food" },
  { id: 111, title: "Handmade" },
  { id: 112, title: "Health & Household" },
  { id: 113, title: "Home & Kitchen" },
  { id: 114, title: "Industrial & Scientific" },
  { id: 115, title: "Luggage & Travel Gear" },
  { id: 116, title: "Movies & TV" },
  { id: 117, title: "Musical Instruments" },
  { id: 118, title: "Office Products" },
  { id: 119, title: "Pet Supplies" },
  { id: 120, title: "Software" },
  { id: 121, title: "Sports & Outdoors" },
  { id: 122, title: "Tools & Home Improvement" },
  { id: 123, title: "Toys & Games" },
  { id: 124, title: "Video Games" },
  { id: 125, title: "Clothing, Shoes & Jewelry" },
  { id: 126, title: "Men" },
  { id: 127, title: "Women" },
  { id: 128, title: "Girls" },
  { id: 129, title: "Boys" },
  { id: 130, title: "Baby" },
  { id: 131, title: "Collectibles & Fine Art" },
  { id: 132, title: "Credit and Payment Cards" },
  { id: 133, title: "Everything Else" },
  { id: 134, title: "Gift Cards" },
  { id: 135, title: "Kindle Store" },
  { id: 136, title: "Amazon Fresh" },
  { id: 137, title: "Amazon Pantry" },
  { id: 138, title: "Prime Video" },
  { id: 139, title: "Smart Home" },
  { id: 140, title: "Home Services" },
  { id: 141, title: "Local Services" },
  { id: 142, title: "Amazon Warehouse" },
  { id: 143, title: "Amazon Business" },
  { id: 144, title: "Today’s Deals" },
  { id: 145, title: "New Releases" },
  { id: 146, title: "Best Sellers" },
  { id: 147, title: "Customer Service" },
  { id: 148, title: "Registry" },
  { id: 149, title: "Gift Finder" },
  { id: 150, title: "Sell" },
  { id: 151, title: "Coupons" },
  { id: 152, title: "Find a Gift" },
  { id: 153, title: "Whole Foods" },
  { id: 154, title: "Free Shipping" },
  { id: 155, title: "Subscribe & Save" },
  { id: 156, title: "Amazon Assistant" },
  { id: 157, title: "Amazon Photos" },
];
