export const allItems = [
  { id: 100, title: "All Departments" },
  { id: 101, title: "Arts & Crafts" },
  { id: 102, title: "Automotive" },
  { id: 103, title: "Baby" },
  { id: 104, title: "Beauty & Personal Care" },
  { id: 105, title: "Books" },
  { id: 106, title: "Computers" },
  { id: 107, title: "Digital Music" },
  { id: 108, title: "Electronics" },
  { id: 109, title: "Garden & Outdoor" },
  { id: 110, title: "Grocery & Gourmet Food" },
  { id: 111, title: "Handmade" },
  { id: 112, title: "Health & Household" },
  { id: 113, title: "Home & Kitchen" },
  { id: 114, title: "Industrial & Scientific" },
  { id: 115, title: "Luggage & Travel Gear" },
  { id: 116, title: "Movies & TV" },
  { id: 117, title: "Musical Instruments" },
  { id: 118, title: "Office Products" },
  { id: 119, title: "Pet Supplies" },
  { id: 120, title: "Software" },
  { id: 121, title: "Sports & Outdoors" },
  { id: 122, title: "Tools & Home Improvement" },
  { id: 123, title: "Toys & Games" },
  { id: 124, title: "Video Games" },
  { id: 125, title: "Clothing, Shoes & Jewelry" },
  { id: 126, title: "Men" },
  { id: 127, title: "Women" },
  { id: 128, title: "Girls" },
  { id: 129, title: "Boys" },
  { id: 130, title: "Baby" },
  { id: 131, title: "Collectibles & Fine Art" },
  { id: 132, title: "Credit and Payment Cards" },
  { id: 133, title: "Everything Else" },
  { id: 134, title: "Gift Cards" },
  { id: 135, title: "Kindle Store" },
  { id: 136, title: "Amazon Fresh" },
  { id: 137, title: "Amazon Pantry" },
  { id: 138, title: "Prime Video" },
  { id: 139, title: "Smart Home" },
  { id: 140, title: "Home Services" },
  { id: 141, title: "Local Services" },
  { id: 142, title: "Amazon Warehouse" },
  { id: 143, title: "Amazon Business" },
  { id: 144, title: "Today’s Deals" },
  { id: 145, title: "New Releases" },
  { id: 146, title: "Best Sellers" },
  { id: 147, title: "Customer Service" },
  { id: 148, title: "Registry" },
  { id: 149, title: "Gift Finder" },
  { id: 150, title: "Sell" },
  { id: 151, title: "Coupons" },
  { id: 152, title: "Find a Gift" },
  { id: 153, title: "Whole Foods" },
  { id: 154, title: "Free Shipping" },
  { id: 155, title: "Subscribe & Save" },
  { id: 156, title: "Amazon Assistant" },
  { id: 157, title: "Amazon Photos" },
];

export const middleList = [
  {
    _id: 2221,
    title: "Get to Know Us",
    listItems: [
      {
        _id: "001",
        listData: [
          "Careers",
          "Blog",
          "About Amazon",
          "Investor Relations",
          "Amazon Devices",
          "Amazon Tours",
          "Press & Media",
        ],
      },
    ],
  },
  {
    _id: 2222,
    title: "Make Money with Us",
    listItems: [
      {
        _id: "002",
        listData: [
          "Sell products on Amazon",
          "Sell apps on Amazon",
          "Become an Affiliate",
          "Advertise Your Products",
          "Self-Publish with Us",
          "Host an Amazon Hub",
        ],
      },
    ],
  },
  {
    _id: 2223,
    title: "Amazon Payment Products",
    listItems: [
      {
        _id: "003",
        listData: [
          "Amazon Rewards Visa Signature Cards",
          "Amazon Store Card",
          "Amazon Secured Card",
          "Amazon Business Card",
          "Amazon Business Line of Credit",
          "Shop with Points",
          "Credit Card Marketplace",
          "Reload Your Balance",
          "Amazon Currency Converter",
        ],
      },
    ],
  },
  {
    _id: 2224,
    title: "Let Us Help You",
    listItems: [
      {
        _id: "004",
        listData: [
          "Amazon and COVID-19",
          "Your Account",
          "Your Orders",
          "Shipping Rates & Policies",
          "Amazon Prime",
          "Returns & Replacements",
          "Manage Your Content and Devices",
          "Amazon Assistant",
          "Help",
        ],
      },
    ],
  },
];

export const footerBottomItem = [
  {
    _id: 1001,
    title: "Book Depository",
    des: "Books with free delivery worldwide",
  },
  {
    _id: 1002,
    title: "Amazon Music",
    des: "Stream millions of songs",
  },
  {
    _id: 1003,
    title: "Amazon Advertising",
    des: "Find, attract, and engage customers",
  },
  {
    _id: 1004,
    title: "Amazon Drive",
    des: "Cloud storage from Amazon",
  },
  {
    _id: 1005,
    title: "6pm",
    des: "Score deals on fashion brands",
  },
  {
    _id: 1006,
    title: "AbeBooks",
    des: "Books, art & collectibles",
  },
  {
    _id: 1007,
    title: "ACX",
    des: "Audiobook Publishing Made Easy",
  },
  {
    _id: 1008,
    title: "Alexa",
    des: "Actionable Analytics for the Web",
  },
  {
    _id: 1009,
    title: "Sell on Amazon",
    des: "Start a Selling Account",
  },
  {
    _id: 1010,
    title: "Amazon Business",
    des: "Everything For Your Business",
  },
  {
    _id: 1011,
    title: "AmazonGlobal",
    des: "Ship Orders Internationally",
  },
  {
    _id: 1012,
    title: "Home Services",
    des: "Experienced Pros Happiness Guarantee",
  },
  {
    _id: 1013,
    title: "Amazon Ignite",
    des: "Sell your original Digital Educational Resources",
  },
  {
    _id: 1014,
    title: "Amazon Web Services",
    des: "Scalable Cloud Computing Services",
  },
  {
    _id: 1015,
    title: "Audible",
    des: "Listen to Books & Original Audio Performances",
  },
  {
    _id: 1016,
    title: "Book Depository",
    des: "Books With Free Delivery Worldwide",
  },
  {
    _id: 1017,
    title: "Box Office Mojo",
    des: "Find Movie Box Office Data",
  },
  {
    _id: 1018,
    title: "ComiXology",
    des: "Thousands of Digital Comics",
  },
  {
    _id: 1019,
    title: "DPReview",
    des: "Digital Photography",
  },
  {
    _id: 1020,
    title: "Fabric",
    des: "Sewing, Quilting & Knitting",
  },
  {
    _id: 1021,
    title: "Goodreads",
    des: "Book reviews & recommendations",
  },
  {
    _id: 1022,
    title: "IMDb",
    des: "Movies, TV & Celebrities",
  },
  {
    _id: 1023,
    title: "IMDbPro",
    des: "Get Info Entertainment Professionals Need",
  },
  {
    _id: 1024,
    title: "Kindle Direct Publishing",
    des: "Indie Digital & Print Publishing Made Easy",
  },
  {
    _id: 1025,
    title: "Prime Video Direct",
    des: "Video Distribution Made Easy",
  },
  {
    _id: 1026,
    title: "Shopbop",
    des: "Designer Fashion Brands",
  },
  {
    _id: 1027,
    title: "Woot!",
    des: "Deals and Shenanigans",
  },
  {
    _id: 1028,
    title: "Zappos",
    des: "Shoes & Clothing",
  },
  {
    _id: 1029,
    title: "Ring",
    des: "Smart Home Security Systems",
  },
  {
    _id: 1030,
    title: "eero WiFi",
    des: "Stream 4K Video in Every Room",
  },
  {
    _id: 1031,
    title: "Blink",
    des: "Smart Security for Every Home",
  },
  {
    _id: 1032,
    title: "Neighbors App",
    des: "Real-Time Crime & Safety Alerts",
  },
  {
    _id: 1033,
    title: "Amazon Subscription Boxes",
    des: "Top subscription boxes – right to your door",
  },
  {
    _id: 1034,
    title: "PillPack",
    des: "Pharmacy Simplified",
  },
  {
    _id: 1035,
    title: "Amazon Renewed",
    des: "Like-new products you can trust",
  },
];
